### ISSUE TITLE
high DP with low AD and missing GT

### ISSUE THREAD

**Issue by ray1919** [Illumina/Pisces#20]
I use pisces to call variants in dozens of sample amplicon sequencing data. I found some confusing results which have high DP, but AD is quite low ,and many of them have GT of .

How should I explain it? Thank you for your time.

```
chr4  69098620  .  T  .  94   PASS  DP=22283  GT:GQ:AD:DP:VF:NL:SB  ./.:0:321:22283:0.986:20:-50.6481
chr4  69098620  .  T  .  100  PASS  DP=21609  GT:GQ:AD:DP:VF:NL:SB  0/.:0:10559:21609:0.511:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=30776  GT:GQ:AD:DP:VF:NL:SB  0/.:0:14548:30776:0.527:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=12768  GT:GQ:AD:DP:VF:NL:SB  0/.:0:6289:12768:0.507:20:-100.0000
chr4  69098620  .  T  .  77   PASS  DP=19007  GT:GQ:AD:DP:VF:NL:SB  ./.:0:271:19007:0.986:20:-41.8536
chr4  69098620  .  T  .  100  PASS  DP=27308  GT:GQ:AD:DP:VF:NL:SB  0/.:0:13466:27308:0.507:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=19015  GT:GQ:AD:DP:VF:NL:SB  0/.:0:9403:19015:0.505:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=21703  GT:GQ:AD:DP:VF:NL:SB  ./.:0:417:21703:0.981:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=16713  GT:GQ:AD:DP:VF:NL:SB  ./.:0:365:16713:0.978:20:-100.0000
chr4  69098620  .  T  .  86   PASS  DP=27426  GT:GQ:AD:DP:VF:NL:SB  ./.:0:377:27426:0.986:20:-44.9136
chr4  69098620  .  T  .  96   PASS  DP=24320  GT:GQ:AD:DP:VF:NL:SB  ./.:0:347:24320:0.986:20:-50.1255
chr4  69098620  .  T  .  100  PASS  DP=24201  GT:GQ:AD:DP:VF:NL:SB  ./.:0:432:24201:0.982:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=24424  GT:GQ:AD:DP:VF:NL:SB  0/.:0:11552:24424:0.527:20:-100.0000
chr4  69098620  .  T  .  90   PASS  DP=27046  GT:GQ:AD:DP:VF:NL:SB  ./.:0:375:27046:0.986:20:-46.8577
chr4  69098620  .  T  .  100  PASS  DP=23484  GT:GQ:AD:DP:VF:NL:SB  ./.:0:382:23484:0.984:20:-91.5446
chr4  69098620  .  T  .  100  PASS  DP=34681  GT:GQ:AD:DP:VF:NL:SB  ./.:0:3559:34681:0.897:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=25040  GT:GQ:AD:DP:VF:NL:SB  0/.:0:12007:25040:0.520:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=30642  GT:GQ:AD:DP:VF:NL:SB  0/.:0:14673:30642:0.521:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=35442  GT:GQ:AD:DP:VF:NL:SB  0/.:0:17160:35442:0.516:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=22501  GT:GQ:AD:DP:VF:NL:SB  0/.:0:11541:22501:0.487:20:-100.0000
chr4  69098620  .  T  .  89   PASS  DP=23863  GT:GQ:AD:DP:VF:NL:SB  ./.:0:337:23863:0.986:20:-48.1045
chr4  69098620  .  T  .  100  PASS  DP=21245  GT:GQ:AD:DP:VF:NL:SB  0/0:100:20333:21245:0.043:20:-100.0000
chr4  69098620  .  T  .  47   PASS  DP=26942  GT:GQ:AD:DP:VF:NL:SB  ./.:0:340:26942:0.987:20:-27.0736
chr4  69098620  .  T  .  100  PASS  DP=17395  GT:GQ:AD:DP:VF:NL:SB  0/0:100:16684:17395:0.041:20:-100.0000
chr4  69098620  .  T  .  0    q30   DP=31880  GT:GQ:AD:DP:VF:NL:SB  ./.:0:259:31880:0.992:20:0.0000
chr4  69098620  .  T  .  100  PASS  DP=21016  GT:GQ:AD:DP:VF:NL:SB  ./.:0:358:21016:0.983:20:-99.6703
chr4  69098620  .  T  .  100  PASS  DP=22311  GT:GQ:AD:DP:VF:NL:SB  0/.:0:10719:22311:0.520:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=23113  GT:GQ:AD:DP:VF:NL:SB  0/.:0:11595:23113:0.498:20:-100.0000
chr4  69098620  .  T  .  36   PASS  DP=28652  GT:GQ:AD:DP:VF:NL:SB  ./.:0:348:28652:0.988:20:-21.4627
chr4  69098620  .  T  .  100  PASS  DP=18506  GT:GQ:AD:DP:VF:NL:SB  0/0:100:17752:18506:0.041:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=29486  GT:GQ:AD:DP:VF:NL:SB  ./.:0:1057:29486:0.964:20:-100.0000
chr4  69098620  .  T  .  100  PASS  DP=22808  GT:GQ:AD:DP:VF:NL:SB  0/.:0:11116:22808:0.513:20:-100.0000

```

**Comment by tamsen** [comment]
Hi! Thanks for your interest in Pisces.

Those are some very unusual looking results.  DP is the total (filtered) depth. AD is the allele depth, reference if its just one number.  The "." in Pisces means an unknown allele. Pisces is detecting an allele that is neither reference nor alternate at those loci. It is telling you it can't confidently call anything at the ./. spots, and it sees reference and "something not reference" at the "0/." spots.

I'm not sure what is going on but here are some thoughts:
Your overall DP is fluctuating wildly from loci to loci.  Is your basecall quality very spotty? Something in your bam that isn't ACGT? Could there be a big spanning deletion or MNV upstream of this region? What was your command line?

Best regards
Tamsen

**Comment by ray1919** [comment]
Thank you for your reply.

1. The DP is fluctuating because all these lines were extracted from different vcf files, so DP is different

2. Only ACGT is presented in the reads

3. I find the position before this position was a MNV, like following

```
|#CHROM|POS     |ID|REF|ALT|QUAL|FILTER|INFO   |FORMAT              |SAMPLE1                                 |
|chr10 |94842863|. |G  |.  |100 |PASS  |DP=2900|GT:GQ:AD:DP:VF:NL:SB|0/0:100:2900:2900:0.000:20:-100.0000    |
|chr10 |94842864|. |T  |.  |100 |PASS  |DP=2849|GT:GQ:AD:DP:VF:NL:SB|0/0:100:2839:2849:0.004:20:-100.0000    |
|chr10 |94842865|. |CA |TG |100 |PASS  |DP=2874|GT:GQ:AD:DP:VF:NL:SB|1/1:100:442,2432:2874:0.846:20:-100.0000|
|chr10 |94842866|. |A  |.  |100 |PASS  |DP=2889|GT:GQ:AD:DP:VF:NL:SB|./.:0:202:2889:0.930:20:-100.0000       |
|chr10 |94842867|. |T  |.  |100 |PASS  |DP=2878|GT:GQ:AD:DP:VF:NL:SB|0/0:100:2877:2878:0.000:20:-100.0000    |
```

If I change **--callmnvs true** to **false**, the two position will be called separately.

**But, I have another question, will "--callmnvs false" option cause Pisces not to call insertions or deletions?**

**Comment by tamsen** [comment]
Hi! Sorry for the late response. I've been doing a lot of travelling the last few months.

> will "--callmnvs false" option cause Pisces not to call insertions or deletions?
Nope. insertions and deletions will still be called.

>whats up with 
|chr10 |94842865|. |CA |TG |100 |PASS  |DP=2874|GT:GQ:AD:DP:VF:NL:SB|1/1:100:442,2432:2874:0.846:20:-100.0000|
|chr10 |94842866|. |A  |.  |100 |PASS  |DP=2889|GT:GQ:AD:DP:VF:NL:SB|./.:0:202:2889:0.930:20:-100.0000       |
|chr10 |94842867|. |T  |.  |100 |PASS  |DP=2878|GT:GQ:AD:DP:VF:NL:SB|0/0:100:2877:2878:0.000:20:-100.0000    |

That means that for positions 94842865 and 94842866, the reference allele CA is replaced with TG, at 84.6%

At position 94842866, there are not enough bases left (that are not already included in the upstream MNV) to call anything besides the MNV called previously. Basically, refer to the previous line for the GT.
Other callers might write a "0/0" or "1/1" at position 94842866, but to us, that just seemed more likely to be misinterpreted as a secondary allele.

thanks for your interest in Pisces!
