### ISSUE TITLE
Invalid cigar '124I': indel must have anchor 

### ISSUE THREAD

**Issue by jungminchoi** [Illumina/Pisces#22]
Hi all,

Thank you for sharing the software. Currently, I am trying to detect somatic mutations from unmatched tumor samples using Pisces and ran into the error below. I think it is similar to the error message reported by hydriniumh2 below.
Bam files were aligned by BWA-MEM.

```
System.Exception: LEYONFF1.bam: Error processing chr '2': Invalid cigar '124I': indel must have anchor ---> System.IO.InvalidDataException: Invalid cigar '124I': indel must have anchor

   at Pisces.Domain.Models.Read.ValidateCigar(CigarAlignment cigarData, Int32 readLength)

   at Pisces.Domain.Models.Read.UpdateFromBam()

   at Pisces.Domain.Models.Read.Reset(String chromosome, BamAlignment bamAlignment)

   at Pisces.IO.BamFileAlignmentExtractor.GetNextAlignment(Read read)

   at Pisces.Logic.Alignment.AlignmentSource.GetNextRead()

   at Pisces.Logic.SomaticVariantCaller.Execute()

   at Pisces.Processing.Logic.BaseGenomeProcessor.ProcessByBam(BamWorkRequest workRequest, String chrName)

   --- End of inner exception stack trace ---.
```

I would appreciate it if you can offer help to work around it.

Best,
Jungmin

**Comment by tamsen** [comment]
Hi!

Thanks for the helpful feedback. As a workaround, you could just remove reads that are all pattern [X]I from your bam.  (Sorry. Admittedly, that's not a great work around)

In our next release (5.2.10) we will allow unanchored indels. We will just warn and continue processing.

**Comment by jungminchoi** [comment]
Thanks! Do you happen to have a recommendation regarding what tools/command-lines to use for the removal of read with certain patterns from the bam files?

Looking forward to the next release!

**Comment by tamsen** [comment]
I'd use samtools to go bam-> sam, just grep out the offending lines, then sam-> bam
( https://www.digitalocean.com/community/tutorials/using-grep-regular-expressions-to-search-for-text-patterns-in-linux  ) but I'm sure what ever you want to use would work.

**Comment by jungminchoi** [comment]
Thank you for your suggestions. I just wanted to make sure of a way not to truncate the bam format.
