### ISSUE TITLE
no allele 2 AD

### ISSUE THREAD

**Issue by ray1919** [Illumina/Pisces#24]
I found some multi allele position return strange result：

 I call with --crushvcf true --ploidy somatic

`chr11	33700664	.	A	C,G	100	PASS	DP=530703	GT:GQ:AD:DP:VF:NL:SB	0/1:100:402064,127503:530703:0.2403:30:-100.0000`

Why the  result have only two AD values while 3 alleles called?

**Comment by tamsen** [comment]
Hi there,

I don't think we have any use cases for crushvcf on and somatic mode.  IMHO its more readable to have one line per allele (uncrushed) especially for somatic and often for germline.  "Crushing" into standard vcf format (one line per loci) is only something I (grudgingly) recommend only if you are doing diploid calling (limited ploidy) and you really need it. (And even then, I still dont _like_ the convention of one line per loci) 

In your particular case, the two AD correspond to the C and G calls.  But I should probably disable crush on + somatic mode. In our group, we never use those two options together, and so the format of the results are not well tested.
