### ISSUE TITLE
No executable found matching command "dotnet-Pisces.dll Windows 10

### ISSUE THREAD

**Issue by YalithKBK** [Illumina/Pisces#27]
I'm new to working with dotnet things and Visual Studio projects. Do these files need to reside in a particular place? I don't have admin access so I just have them sitting in my Documents folder.

**Comment by tamsen** [comment]
Hi,

Are you compiling yourself, or running from the released binaries? Check this -

1) do you have dotnet installed? If you go to your cmd prompt and type dotnet, does it work?
> dotnet

2)now try 
>dotnet {your\\full\path\to\pisces.dll}

**Comment by YalithKBK** [comment]
I had to put in the full path name to the dll (still new to this). Thank you!
