### ISSUE TITLE
homozygous allele frequency cutoff too high

### ISSUE THREAD

**Issue by mcgml** [Illumina/Pisces#4]
Hi

I just analysed some amplicon sequencing using Pisces 5.1.6.54 with the following settings:

`mono /share/apps/pisces-distros/5.1.6.54/Pisces.exe \
-B ./"$seqId"_"$sampleId".bam \
-MinimumFrequency 0.01 \
-g /data/db/human/gatk/2.8/b37 \
-i "$panel"_ROI_b37_thick.bed \
-MinMQ 20 \
-t 12`

A call at 98.9% allele frequency was called heterozygous:
`GT:AD:DP:GQ:NL:SB:VF    0/1:10,862:872:99:20:-100:0.989`

Can I lower the het allele frequency cutoff to 98%?

Thanks
Matt

**Comment by tamsen** [comment]
Hi Matt

Pisces is by default a somatic caller, looking for 1% variants in a heterogeneous sample. If it detects 98.9% of the alt allele and 1% reference allele, it will consider that evidence for heteroplasmy and report a het call. 

You may change the default minimum frequency on the command line: MinimumFrequency or MinVF
https://github.com/Illumina/Pisces/wiki/Pisces-5.1.6-Supported-Options

If you want the het "0/1" designation to reflect what you would expect for a diploid model, set -ploidy diploid.  The model is simple, and DiploidGenotypeParameters will allow you to make adjustments for your assay if you need to.

**Comment by mcgml** [comment]
@tamsen thanks for getting back to me. Sorry I wasn't clear -- I used your tool for tumour analysis (which performs very well!) but I wondered if it would be possible to get 1/1 for a 98.9% variant?

Thanks
Matt

**Comment by tamsen** [comment]
I'm glad its working well for you!

Hopefully this helps with your question, if I understand it. There are two ways to do what you want.

1)
A 98.9% alt call will *always* be 1/1 for Pisces in diploid mode.  Ie, append -ploidy diploid to your command line, and re-run.

or

2) set -MinimumFrequency 0.02 on your command line and rerun. This will keep you in somatic mode, but raises the threshold of a qualifying allele to 2%. So, in your example,  if 98.9% of an alt is detected and only 1.1% of a reference. Once the limit of detection is raised to 2%, this reference is now falls under our detection limits. So Pisces will only "see" the alt allele and no evidence for reference -> resulting in a homozygous alt GT (1/1)

**Comment by mcgml** [comment]
@tamsen thanks option 2 solved it! This is much more complication than I originally thought. Thanks for your time.
