### ISSUE TITLE
5.2.11.163 tarballs not in gzip format?

### ISSUE THREAD

**Issue by hansenaw** [Illumina/Pisces#42]
Trying to unpack two tarballs for v5.2.11.163 – `CreateGenomeSizeFile` as well as `Gemini`. Same error with both. Can't seem to open the files with `tar -xzf` or with `gunzip`. No problem with this version of the Pisces binaries.

```
tar -xzf CreateGenomeSizeFile_5.2.11.163.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by Aargol** [comment]
same error occurs, any progress?

**Comment by hansenaw** [comment]
Any updates? Haven't heard anything about this.

I will try using previous versions of other pisces recommended pipeline components together with the newest version of Pisces. Please let me know if there are any reasons I shouldn't be doing this.

**Comment by hansenaw** [comment]
Issue resolved... I was using the wrong download link from GitHub!

Incorrect link: `https://github.com/Illumina/Pisces/blob/master/binaries/5.2.11.163/GeminiMulti_5.2.11.163.tar.gz`

Correct link:
`https://github.com/Illumina/Pisces/raw/master/binaries/5.2.11.163/GeminiMulti_5.2.11.163.tar.gz`

Needed to actually click into the individual files and access the download link there, rather than the file-level links visible from the `/5.2.11.163/` folder page.
