### ISSUE TITLE
Should be compiled under a supported .NET core version

### ISSUE THREAD

**Issue by jstaf** [Illumina/Pisces#7]
Had a bit of fun trying to get this to work on Centos 7 just now. It turns out that Pisces won't run unless you have the exact 1.0.4 .NET runtime and can't use the LTS version 1.1.4 from the official Microsoft download site.

So I had to go digging through the archives to find the correct version, turns out you need the version of .NET core from https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.5-download.md

Perhaps compile this for the currently supported 1.1.4 LTS from here: https://www.microsoft.com/net/download/linux ?

**Comment by tamsen** [comment]
Thanks for the feedback, and sorry for the annoyance. We will try to make this better going forward.

**Comment by jstaf** [comment]
Awesome, appreciate the effort! (Also just wanted to post this here so others had a link to the current .NET core version in the interim)

**Comment by tamsen** [comment]
If you get a chance please let us know if this is now fixed in v5.2.5.20 (.net core 2.0) .
Thank you!
